### ISSUE TITLE
tcpattach/unixattach api

### ISSUE THREAD

**Issue by ebfe** [sustrik/libmill#108]
Maybe {tcp,unix}attach should take another argument to indicate wether the given fd is listening or not. The autodetection seems to only work on Linux and FreeBSD and I'm not sure if there is really a usecase where you want to attach to an fd and don't know wether it is a listening or connected socket.

**Comment by reqshark** [comment]
I think the issue here for attach/detach is needing documentation on those calls. 

can we talk about what those calls do?

**Comment by sustrik** [comment]
attach takes fd and creates a socket object. detach takes socket object, destroys it without closing the underlying fd and returns the fd.

And yes, if OSes don't support autodetection, then adding a parameter would make sense.
