### ISSUE TITLE
Core dump

### ISSUE THREAD

**Issue by jimjag** [sustrik/libmill#110]
Under OSX, the following test results in a core-dump BUT the test itself appears to PASS:

Process:               chan [16616]
Path:                  /Users/USER/*/chan
Identifier:            chan
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        chan [16602]
Responsible:           iTerm [421]
User ID:               501

Date/Time:             2015-09-10 10:47:53.999 -0400
OS Version:            Mac OS X 10.10.5 (14F27)
Report Version:        11
Anonymous UUID:        D833ECC0-5E70-9179-BE00-CCBECD4DDFB6

Time Awake Since Boot: 260000 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
crashed on child side of fork pre-exec

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff8fe54286 __pthread_kill + 10
1   libsystem_c.dylib             	0x00007fff896f19b3 abort + 129
2   libmill.7.dylib               	0x000000010be130d7 mill_panic + 39
3   libmill.7.dylib               	0x000000010be10a1b mill_wait + 59 (poller.c:162)
4   libmill.7.dylib               	0x000000010be0f356 mill_suspend + 102 (cr.c:112)
5   libmill.7.dylib               	0x000000010be0efca mill_chs + 138 (chan.c:322)
6   chan                          	0x000000010be07597 main + 4711 (chan.c:205)
7   libdyld.dylib                 	0x00007fff8bbd45c9 start + 1

/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: tests/example
PASS: tests/go
PASS: tests/cls
PASS: tests/chan
PASS: tests/choose
PASS: tests/sleep
PASS: tests/fdwait
PASS: tests/tcp
PASS: tests/udp
PASS: tests/unix
PASS: tests/signals
PASS: tests/overload
============================================================================
Testsuite summary for libmill 0.10-beta-241-g9be57bf
============================================================================
# TOTAL: 12
# PASS:  12
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0

**Comment by sustrik** [comment]
That's one of the tests that check whether libmill panics as appropriate. Aborting the process in the expected behaviour.

**Comment by nirs** [comment]
Fixed in #112
