### ISSUE TITLE
Provide a way to avoid name clashes

### ISSUE THREAD

**Issue by sustrik** [sustrik/libmill#117]
libmill uses rather generic keywords like 'in' or 'choose'. It may happen that user would want to integrate it with legacy code that's using those identifiers for other purposes.

libmill should define a macro that would switch all the libmill names to mill_-prefixed variants:

    #define LIBMILL_USE_PREFIX
    ...
    mill_choose {
    mill_in(...

**Comment by reqshark** [comment]
indeed, without such a mechanism it's not possible to use libmill inside Apple's Xcode editor (like for iOS)

A Swift/Objective-C language collision occurs for `@end` keyword, a macro defined #end marks the end of an Objective-C Interface, Implementation, etc. see [apple docs basic syntax](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/DefiningClasses/DefiningClasses.html#//apple_ref/doc/uid/TP40011210-CH3-SW6)

```c
#define end \
                    break;\
                }\
            }\
            mill_idx = mill_choose_wait();\
        }
```

capitalizing [#End there in libmill.h](https://github.com/sustrik/libmill/blob/cdbd5e24e99964fdf65e701df099155ff484667e/libmill.h#L247) fixes the issue, and magically makes it work in Xcode

**Comment by sustrik** [comment]
Uh. I often use 'end' as a local variable. I guess none of those programs can be compiled with XCode.

**Comment by reqshark** [comment]
I typically don't use Xcode but sort of necessary for iOS deployment targets.. Anyway with all this Xcode talk, I thought I'd share my libmill-ios build script for compiling across iOS architectures:

https://gist.github.com/reqshark/640aa97229e29d021b5e

**Comment by kellytk** [comment]
I agree with the goal of this issue.  I consider C library API being [optionally] prefixed good practice.

**Comment by sustrik** [comment]
Want to give it a try? Patches are welcome.

**Comment by kellytk** [comment]
If the issue is unresolved by the time I next work on a project I'd like to try libmill with, I'll likely consider it.  Regarding design, prefixing elements of public API with "mill_" would be a straightforward place to begin.  First however, SQLite is a mature C library and I would be inclined to review its handling of the issue.

**Comment by sustrik** [comment]
Fixed.
