### ISSUE TITLE
dns_resolve_conf on osx

### ISSUE THREAD

**Issue by reqshark** [sustrik/libmill#124]
hmm, all the tests pass, but when i update & load the library as I typically do, a new issue presents. do we need to need to export `dns_resconf_local`? I'm getting:

```bash
dyld: Symbol not found: _dns_resconf_local
```

**Comment by sustrik** [comment]
Interesting. Does it still happen with the very latest version?

In any case, exporting dns_resconf_local doesn't make sense as it's only used internally.

**Comment by reqshark** [comment]
nevermind Marin, I apologise--my mistake, wasn't even loading `libmill/dns/dns.c`, now it's ok! :)
