### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by reqshark** [sustrik/libmill#128]
what's up with the travis build error? Is there really an error or do we need to fix the cmake configuration?

cc: @procedural, @nickdesaulniers

**Comment by sustrik** [comment]
It's just CMake. There's a new test that has a file piped to stdin. CMake script has to be modified to account for that.

**Comment by reqshark** [comment]
nice fix 23d05e874542dc12ef502644c5d2cff50844ce4e!

**Comment by sustrik** [comment]
It seems that CTest doesn't support piping files into stdout. Shrug.
