### ISSUE TITLE
mfork: closing kqueue file descriptor is unsuccessful and leads to 'assert failed' on OSX

### ISSUE THREAD

**Issue by Danappelxx** [sustrik/libmill#131]
Minimal program to reproduce:
```c
#include <libmill.h>

int main(int argc, char *argv[]) {
  goprepare(10, 25000, 300);
  pid_t pid = mfork();
}
```

compiled with:
```shell
clang -o main main.c libmill.dylib -I/usr/local/include
```

output:
```shell
Assert failed: rc == 0 (./kqueue.inc:92)
```

Using libmill version 1.5 downloaded from the website and compiled with 
```shell
./configure && make && sudo make install
```

I'm on OSX 10.11 running clang 7.3.0.

My knowledge of c is very limited but it seems like the assumption made about kqueue in the doc comment ([here](https://github.com/sustrik/libmill/blob/master/kqueue.inc#L87) about how closing it will not return an error) is misguided.

As expected, if I get rid of the `goprepare(10, 25000, 300)` the fork succeeds.

Let me know if there's anything I can do!

**Comment by nirs** [comment]
Maybe we should include errno in the error message in these asserts?

```
Assert failed: rc == 0 (rc=2, errno=13 file=./kqueue.inc:92)
```

**Comment by sustrik** [comment]
EACCESS. Interesting. I wonder whether that means that "file descriptor haven't survived the fork." Anyway, I'll try to fix it.

As for including errno into the asserts, yes, something like assert_errno() would be nice. I am to lazy to implement it though. So it's up to you :)

**Comment by sustrik** [comment]
The problem is now fixed. Tested on OSX (via Travis) and FreeBSD.

Please check and close the ticket if everything goes OK.

**Comment by Danappelxx** [comment]
Seems to work! Thanks for the quick fix :)
