### ISSUE TITLE
When will coroutines switch execution? 

### ISSUE THREAD

**Issue by arafath-mk** [sustrik/libmill#136]
In Go goroutines switch execution on blocking IO operations like file rated or write to a file in hard disk. Does the libmill have the similar behavior?

**Comment by sustrik** [comment]
Yes, but you must used the blocking functions provided by libmill library (i.e. msleep() instead of sleep() etc.)

**Comment by arafath-mk** [comment]
Thanks sustrik.
There are examples for network IO in libmill. Could you please give me an example for file IO?

**Comment by sustrik** [comment]
https://raw.githubusercontent.com/sustrik/libmill/master/tests/file.c

**Comment by arafath-mk** [comment]
Thanks.
