### ISSUE TITLE
Simple example has unexpected behaviour

### ISSUE THREAD

**Issue by Zentdayn** [sustrik/libmill#138]
I went on following the tutorial and i tried to make a simple program that would just send back everything that it receives.

https://gist.github.com/Zentdayn/f8613aa8b419d846dc27630be086cb0d

Could someone tell me what's wrong with this?

I seems like tcprecv blocks forever. Changing the timeout to 0 makes it work but the cicle just runs a lot of times, and that's not what i wanted to do. I want it to block until it receives something.

**Comment by sustrik** [comment]
It sends a reply afte receiving 512 bytes. Is that what you are want it to do?

**Comment by Zentdayn** [comment]
Is reading 1 byte at a time the only way to get notified "early", that is even if the buffer isn't filled completely ? ( without being actively waiting )

I want to parse a protocol with a variable message size how could i do it? 

I can't tcprecv(buf) ( with  buf being some buffer with a length equal to the maximum length a message could have ) because shorter messages than that would never leave tcprecv.

**Comment by sustrik** [comment]
Have you looked at tcprecvuntil()?

**Comment by Zentdayn** [comment]
Yup. That works fine, but it requires me to have a special marker to end messages.

So if i want to parse some message that has a format such as messageID, messageLength, Data i can't use tcprecvuntil right?

**Comment by sustrik** [comment]
```
tcprecv(&id, 4);
tcprecv(&length, 4);
tcprecv(buf, length);
```

**Comment by Zentdayn** [comment]
Uh that was pretty dumb on my part.

Thanks for your insights.
