### ISSUE TITLE
defer() implementation

### ISSUE THREAD

**Issue by 7cbfe38c11c70bec16f03f8c69d4be99** [sustrik/libmill#142]
I noticed this recently - https://github.com/google/nsjail/blob/db4a90d22542d3642b4a34fe6c2a9358c3414c69/common.h and thought it may be of interest to you, in the off chance you were ever wondering how to support a defer() type implementation in libmill.

**Comment by sustrik** [comment]
No need to do this in libmill. Users are free to use the cleanup attribute themselves if they feel like it.

**Comment by 7cbfe38c11c70bec16f03f8c69d4be99** [comment]
Fair enough - thought it might have been a nice abstraction you may have been interested in adding.

Thanks for your work on libmill - I enjoy using it :)
