### ISSUE TITLE
Assert failed: rc == FDW_OUT (tcp.c:289)

### ISSUE THREAD

**Issue by cnchar** [sustrik/libmill#143]
Hi sustrik.
    We find a bug in this test demo, so we have this question for you.
When we run this code, we do not expect this auto crush result. How can we fix it?
`
#include <stdlib.h>
#include <string.h>
#include <libmill.h>
#include <error.h>
#define MAX_SIZE 2048

coroutine void verifyClient(tcpsock sock)
{
    void* buffer = alloca(MAX_SIZE);
    for(;;)
    {
        size_t sz = tcpsend(sock, buffer, MAX_SIZE, -1);
        if(errno) { break; }
        tcpflush(sock, -1);
        if(errno) { break; }
    }
    tcpclose(sock);
}

coroutine void client()
{
    msleep(now()+100);
    ipaddr addr = ipremote("127.0.0.1", 8888, 0, -1);
    tcpsock conn = tcpconnect(addr, -1);
    tcpclose(conn);
}

int main() {
    ipaddr addr = iplocal(NULL, 8888, 0);
    tcpsock ls = tcplisten(addr, -1);
    go(client());
    for(;;)
    {
        tcpsock as = tcpaccept(ls, -1);
        if(!as){continue;}
        go(verifyClient(as));
    }
    tcpclose(ls);
    return 0;
}`

**Comment by sustrik** [comment]
Fixed. Try the mainline version of libmill from github.

**Comment by sustrik** [comment]
I've also released the patch in 1.10 release.

**Comment by cnchar** [comment]
nice job
