### ISSUE TITLE
Do you have any plan to make an http server using libmill?

### ISSUE THREAD

**Issue by arafath-mk** [sustrik/libmill#144]
One can write an application server in C itself, if an http server was available.

**Comment by amitsaha** [comment]
You can see an example here: https://github.com/amitsaha/lj_libmill/tree/master/hashid-service

Its basic as you can see. Feel free to play with it and adopt it for your use case.

**Comment by arafath-mk** [comment]
Thanks. h2o (https://github.com/h2o/h2o) is a full fledged http server with very high performance. How can we develop an http server using libmill and referring the architecture and features of h2o server? Are you interested to do such a project?
