### ISSUE TITLE
Thread pool / scheduler

### ISSUE THREAD

**Issue by theduke** [sustrik/libmill#145]
Do you have any thoughts / an interest in expanding libmill to distribute the coroutines over multiple threads with a scheduler, like Go does for example, to allow an application to take advantage of multiple cores?

Or do you consider that completely out of scope?

**Comment by sustrik** [comment]
Why would you want to do that? On one hand there are coroutines: fast, single-core and no failure isolation. On the other hand there are processes: slow, multi-core with failure isolation. What's the use case for having something in the middle?

**Comment by theduke** [comment]
Well, for me, that's a big point of coroutines.
Most languages that implement a CSP / coroutine methodology agree...

Here's a great description of the GO scheduler: http://morsmachine.dk/go-scheduler

Coroutines allow you to write simple, concurrent code that just communicates with channels, without worrying about the underlying implementation on the OS level.
 
Most programs are not only IO bound! And with the increasing number of cores, one of the biggest points of using CSP is utilizing more than one core without having to think about it much.

I want to write a program where I can just offload a possibly CPU intensive task to the background without having to worry about starting a new thread or doing IPC. Both threads and processes have heavy overhead and and are an implementation detail.

A scheduler starts multiple threads, distributes the coroutines to run  queues inside those threads, and can move them around between threads if a certain routine is,  for example, CPU bound.

Of course, such a scheduler has an overhead, and you can most likely get better performance with starting worker threads for each core and  manually distributing the workload, but as has been shown time and time again, this is error prone, especially for not so good programmers (deadlocks, overhad for threads, ipc,  ...) 

Just my opinion.

**Comment by sustrik** [comment]
Two quick comments:

1. Doing it is probably impossible, unless one relies on undefined behaviour of the underlying pthreads library.

2. I am not sure it's even desirable. Eventually, applications have to scale to multiple machines. Adding an intermediate step that allows scaling to N cores on a single machine is a waste of work given that the implementation would contain nothing that could be possibly reused for scaling on multiple machines.
