### ISSUE TITLE
Interrupting fdwait() from another coroutine

### ISSUE THREAD

**Issue by jfsmig** [sustrik/libmill#149]
Hi, folks!

I am using coroutines to share message-oriented connections. Each connection has two coroutines: a first "producer" coroutine reads requests from a channel, marshals then writes to the descriptor, a second "consumer" coroutine reads from the descriptor, unmarshals then signals the caller coroutine through a channel.

I would be able to quickly but gracefully shut the connection and stop both coroutines. I currently use the input channel to the producer to send a "stop" message. But if no message is received by the consumer, I am forced to wait for the timeout of its call to `fdwait()`.

I am maybe missing some well-known technique, or maybe my design is wrong (even though it leads to a simple code). But it seems that a specific API function is possible, desirable, and probably easy to write.

I gave a quick try to an implementation of a `void fdbreak(int fd);` that resumes all the coroutines waiting on `fd` with an FDW_ERR event. I easily interrupted the pending `fdwait()`, though I still break an assert, obciously due to a lack of knownledge about the library structures. Raising FDW_ERR is a (quick yet poor) idea just for testing purpose, IMO a dedicated event like FDW_INTR (a.k.a. interrupted) is a better idea.

What do you think about? Is it worth I present the patch ?

**Comment by sustrik** [comment]
In golang this is typically done by closing the socket. In C terms, you call shutdown() on the file descriptor and all calls to it start returning errors. When seeing the error the worker coroutine would exit.

**Comment by jfsmig** [comment]
I am so sorry for the delay!

It works like a charm and covers my current needs :)
