### ISSUE TITLE
Testing: setjmp/longjmp in assembly language

### ISSUE THREAD

**Issue by raedwulf** [sustrik/libmill#154]
I have made a preliminary test to see whether there's a significant improvement in an assembly implementation of the context switching code.  On x86-64 there's a 17-18% improvement on the go perf test and 28% improvment in just context switching.

I'll setup a github branch when I get home or find a wifi access point without the ssh ports disabled...

With inline-assembly:
```bash
$ cat /proc/cpuinfo | grep CPU | head -n1
model name      : Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz
$ ./perf/go 10
executed 10M coroutines in 0.780000 seconds
duration of one coroutine creation+termination: 78 ns
coroutine creations+terminatios per second: 12.820512M
$ ./perf/ctxswitch 10
performed 10M context switches in 0.316000 seconds
duration of one context switch: 31 ns
context switches per second: 32.258064M
```

With old sigsetjmp/siglongjmp
```bash
$ cat /proc/cpuinfo | grep CPU | head -n1
model name      : Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz
$ ./perf/go 10
executed 10M coroutines in 0.948000 seconds
duration of one coroutine creation+termination: 94 ns
coroutine creations+terminatios per second: 10.638297M
$ ./ctxswitch 10
performed 10M context switches in 0.437000 seconds
duration of one context switch: 43 ns
context switches per second: 23.255812M
```

**Comment by raedwulf** [comment]
Some more inlining.
```
$ ./perf/ctxswitch 10
performed 10M context switches in 0.266000 seconds
duration of one context switch: 26 ns
context switches per second: 38.461536M
```

**Comment by sustrik** [comment]
!!!

**Comment by paulofaria** [comment]
👍

**Comment by raedwulf** [comment]
https://github.com/raedwulf/libmill/tree/asm

That has my initial code ~32-33 ns per context switch.  The other code is still a bit messy and experimental which I'll merge into this branch.  It does use the GCC-macro return extension (which libdill does as well).  Alternatives include static inline functions in the header or simply fallback to sigsetjmp implementation.

**Comment by sustrik** [comment]
Great, I can try to merge it into the mainline. Are you OK with submitting the patch under MIT/X11 license?

**Comment by raedwulf** [comment]
Yeah MIT/X11 is fine - my preferred :)

**Comment by raedwulf** [comment]
There's a few #ifdefs need to be added as yet before it's release-ready.  For instance, I've not added the #ifdefs to detect whether the target x86-64 platform has YMM registers or not, and it will probably complain if it doesn't.

**Comment by raedwulf** [comment]
Oh and it's not binary-compatible (it is api-compatible though) with older versions of libmill, so I think the version needs bumping.

**Comment by sustrik** [comment]
I am not sure about the ymm register stuff. Looking at other implementations of context switching it seems that they are either ignoring xmm/ymm or using it unconditionally:

https://github.com/jamwt/libtask/blob/master/asm.S#L90
https://github.com/clibs/coro/blob/master/coro.c#L135
https://github.com/halayli/lthread/blob/master/src/lthread.c#L84
https://github.com/Adaptv/ribs2/blob/master/src/context_asm.S#L27
https://github.com/sos22/libcoroutine/blob/master/coroutines.c#L43

I may be missing something here.

**Comment by raedwulf** [comment]
My implementation is inline within a macro so it needs to inform the compiler which registers have been affected by the asm block within any part of the code.  In the other implementations, all the asm blocks are within a function call, and the x86-64 ABI has a set list of registers that are volatile/non-volatile removing the need for them to specify the list of asm instructions cobbered.

The advantage of my approach is that it should be faster to create/destroy coroutines, with the downside that I have to manually specify all the registers on the platform otherwise when a context switch returns to that point, the registers will not be what the other compiler-generated code expects.

**Comment by sustrik** [comment]
Ok, understood. I am looking into how to identify whether ymm is present and there seem to be no such macros. It can be queried using cpuid instruction, but it looks like this is going to be hard to test without access to different hardware.

**Comment by sustrik** [comment]
Hm, there's __builtin_cpu_supports("avx2") but that doesn't seem to be much different from using cpuid.

**Comment by raedwulf** [comment]
I do have a substantial amount of hardware of different x86-64 generations if needs be :)

The register-clobber list is something that is done at compile-time, so a compile time flag should suffice. Runtime checks are not necessary.

We can use `#if defined __AVX__` to see if ymm registers are supported in the libmill/application build.  The YMM registers are used with the AVX instructions.  As the header is compiled with the application, this check will automatically be valid for the target architecture of the application.

**Comment by raedwulf** [comment]
Just committed it.

**Comment by sustrik** [comment]
Doesn't it mean we have to compile libmill with -mavx? What about the case where client application uses AVX, but libmill is compiled without -mavx. Then the client can use YMM register and libmill library can clobber it.

**Comment by raedwulf** [comment]
A long comment... so the TLDR at the start:
Clobbering is more like a constraint that we don't know what the state these variables in the clobber list will be after the asm block.  So when libmill is compiled without -mavx, it won't be using YMM registers at all so there's nothing to constrain (rather than something to clobber).
As long as any piece of code includes the same setjmp implementation, it is fine.

Deeper thoughts on "clobber":
I think they use the word "clobber" because it's taken from the perspective of the block of inline-assembly doing something to memory+registers.  What the compiler does with that information is that it generates code taking into the account that those registers/memory locations can be changed after the block.  If the compiler doesn't know about YMM registers (as in the case of libmill being compiled without -mavx), it won't be generating or modifying YMM registers anyway.  And due to the nature of x86-64 function ABI, these registers are automatically "clobbered" at function call boundaries anyway, so even if an external library was called that did used YMM, the compiler knows that it can't use the YMM across the boundary and will need to reload it from memory.

**Comment by raedwulf** [comment]
I just pushed a commit that uses the "memory" clobber ~ it's slightly slower but means we won't need to explicitly specify registers (and thus avoid the AVX/YMM issue entirely!)) and it is a bit more conservative so probably won't trigger any compiler mishaps.

```bash
$ ./perf/ctxswitch 10
performed 10M context switches in 0.284000 seconds
duration of one context switch: 28 ns
context switches per second: 35.714283M
```

down from:
``bash
$ ./perf/ctxswitch 10
performed 10M context switches in 0.266000 seconds
duration of one context switch: 26 ns
context switches per second: 38.461536M
```

**Comment by sustrik** [comment]
Submitted. All tests pass: https://travis-ci.org/sustrik/libmill/builds/147793010

**Comment by raedwulf** [comment]
Excellent! I'll get working on a 32-bit version and a ARM version (at some point, i've not setup my ARM SBCs recently).

**Comment by sustrik** [comment]
Btw, I have ported the patch to libdill and the tests on Travis fail in lot of cases. Specifically, the tests the involve forking fail in sigsegv. Do you have an idea what may be the problem? Unfortunately, the test succeed on my box :|

**Comment by raedwulf** [comment]
Hi, I just tested libdill as well and it works fine here.  I'm currently reading the travis logs and it appears most the errors occur on clang with the exception with Mac OS X's gcc.  I can test clang, and see if I can reproduce it here.  Chances are it's the same issue.

**Comment by raedwulf** [comment]
I found the bug - the "memory" clobber only seems to clear the registers on gcc/linux.  I'll work on a patch to include all the registers.
