### ISSUE TITLE
ssl test not pass

### ISSUE THREAD

**Issue by zii** [sustrik/libmill#168]
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
gcc version 4.9.2 (Debian 4.9.2-10)
OpenSSL 1.0.1t  3 May 2016

./configure --enable-ssl
make
make check
```
====================================
   libmill 1.16: ./test-suite.log
====================================

# TOTAL: 18
# PASS:  17
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/ssl
===============

lt-ssl: tests/ssl.c:72: main: Assertion `ls' failed.

```

**Comment by sustrik** [comment]
Can you check what the errmo is set to?

**Comment by zii** [comment]
lt-ssl: tests/ssl.c:73: main: Assertion `ls' failed.
errno: 2

**Comment by sustrik** [comment]
ENOENT - that looks like cert files are not present. Are you by chance running the tests from directory other than project's root directory?

**Comment by zii** [comment]
Thank you, the pem files are not exists because I download it from [website].(http://libmill.org/download.html)
Then I make it success through git  :)
```
apt-get install libtool openssl libssl-dev
git clone https://github.com/sustrik/libmill.git
cd libmill
./autogen.sh
./configure --enable-ssl
make
make check
make install
ldconfig
```
```
============================================================================
Testsuite summary for libmill 1.16-12-g7766b64
============================================================================
# TOTAL: 18
# PASS:  18
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

```

**Comment by sustrik** [comment]
Right. The files are missing in the tarball. I'll fix that.

**Comment by sustrik** [comment]
Fixed.
