### ISSUE TITLE
msleep() never wakes up (v1.17)

### ISSUE THREAD

**Issue by robertjpayne** [sustrik/libmill#171]
I'm integrating libpq (PostgreSQL client driver) with libmill and one of the tests I have is around concurrent SQL transactions on separate connections in the same process.

To help simulate concurrency I sleep a transaction in the middle to allow a second transaction to begin. While doing so I keep encountering an issue where `msleep` never returns.

At first I figured this was an issue with libpq and threading or something but after debugging a ton @raedwulf suggested I try libdill just to see if it's a bug in libpq or libmill and sure enough using libdill msleep never causes an issue.

Attached is the libmill code and the libdill code. I can't really figure out where the failure scenario is, goredump() displays all the coroutines just fine. Maybe it's worthwhile looking into the timers list and see if it's gone missing?

[dill_main.txt](https://github.com/sustrik/libmill/files/682337/dill_main.txt)
[mill_main.txt](https://github.com/sustrik/libmill/files/682336/mill_main.txt)

When running the sample what happens is Transaction A starts and then half way through it sleeps where `msleep(now() + 2000)` is. Transaction b starts then it sleeps and wakes where `msleep(now() + 500)` is. Transaction B halts in it tracks waiting on data from the server (because on the server it's blocked by Transaction A) but Transaction A never wakes up so it can never continue.

**Comment by robertjpayne** [comment]
Apologies too this is pretty vague on details I'm still actively trying to find some starting point as to why this happens and how to fix it.

**Comment by robertjpayne** [comment]
For what it's worth too the CPU is idle while this happens so it's not in a busy loop and it's actively running a fdwait for Transaction B's file descriptor.

**Comment by sustrik** [comment]
Where does libpq-fe.h come from?

**Comment by robertjpayne** [comment]
@sustrik it's system installed libpq, I've also tested it with a compiled version with threading support disabled just to be extra sure.

There's a minimal amount of pthread code in libpq, mostly they use a mutex to protect a cache that looks up usernames on the current system while connections are made.

**Comment by sustrik** [comment]
Progress report: I've tracked the problem to epoll.inc:213

It should remove the timer of the successful fdwait(IN) operation. In our case there should be no timer given that the deadline is -1. However, cr->timer seems to point to the msleep timer which is living in a different coroutine.

**Comment by sustrik** [comment]
Ok, I think I've found it. Please, check with the current head from github.

**Comment by robertjpayne** [comment]
@sustrik godsend it works thanks 👍

**Comment by sustrik** [comment]
Btw, I've released 1.18 that contains the patch.

**Comment by sustrik** [comment]
And, BTW, if you release the postgres wrapper as an open source project, let me know, we can link it from libmill.org
