### ISSUE TITLE
Spawning a Subprocess

### ISSUE THREAD

**Issue by robertjpayne** [sustrik/libmill#173]
Subprocess as far as I'm aware (posix_spawnp / system) are a combination of forking the current process and then running exec)

I'm struggling to get a working example in libmill of a coroutine spawning a subprocess even in fire and forget mode -- on macOS the kqueue poller always asserts on `crp->in` I can't help but think that the spawned subprocess is inheriting libmill and breaking in a large way.

Is there a sanctioned way to properly launch a subprocess or perhaps something that could be built in?

**Comment by sustrik** [comment]
There's mfork().

**Comment by robertjpayne** [comment]
@sustrik hey sorry this is my fault, for some reason when LLDB is attached to a process with libmill a fork always causes the assert on crp->in (kqueue polling) frustrating but I an turn the debugger off for the pieces of code that use subprocesses.
