### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by ihabbab** [sustrik/libmill#22]
Hi Martin,
I just downloaded and installed 0.7 and I am getting a segmentation fault when I run the example in tests. I am on a MacOS. Any advice?
Thanks,
-Isam

**Comment by sustrik** [comment]
Can you attach the backtrace?

**Comment by ihabbab** [comment]
thanks a lot, here it is, without, and later on with -lmill which does not generate a backtrace
by the way, thanks for your patience, it's been a long time I have not programmed in C

 ~/desktop/gramian/libmill/libmill-0.7-beta/tests> gcc -rdynamic example.c -o example
Undefined symbols for architecture x86_64:
  "_mill_go_epilogue", referenced from:
      _main in cciUzVOj.o
  "_mill_go_prologue", referenced from:
      _main in cciUzVOj.o
  "_mill_msleep", referenced from:
      _worker in cciUzVOj.o
      _main in cciUzVOj.o
  "_mill_unoptimisable1", referenced from:
      _main in cciUzVOj.o
  "_mill_unoptimisable2", referenced from:
      _main in cciUzVOj.o
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status

**************************************************** Now using -lmill

 ~/desktop/gramian/libmill/libmill-0.7-beta/tests> gcc -rdynamic example.c -o example -lmill
 ~/desktop/gramian/libmill/libmill-0.7-beta/tests>

**Comment by sustrik** [comment]
Can you re-build like this:

./configure --disable-shared --enable-debug; make

That should add line numbers to the backtrace.

**Comment by ihabbab** [comment]
I redid the tar, configure as you suggested, and i think i am getting an error in make check. Here is a complete record of it. Thanks.

-------------------------------------------------------------------
 ~/desktop/gramian/libmill> cd libmill-0.7-beta
 ~/desktop/gramian/libmill/libmill-0.7-beta> ls
AUTHORS			configure		list.h			slist.h
COPYING			configure.ac		ltmain.sh		stack.c
ChangeLog		cr.c			m4			stack.h
Makefile.am		cr.h			missing			tcp.c
Makefile.in		debug.c			model.c			test-driver
abi_version.sh		debug.h			model.h			tests
aclocal.m4		depcomp			package_version.sh	utils.c
chan.c			install-sh		perf			utils.h
compile			libmill.h		poller.c		valbuf.c
config.guess		libmill.pc.in		poller.h		valbuf.h
config.sub		list.c			slist.c
 ~/desktop/gramian/libmill/libmill-0.7-beta> ./configure --disable-shared --enable-debug
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '501' is supported by ustar format... yes
checking whether GID '20' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-apple-darwin11.4.2
checking host system type... x86_64-apple-darwin11.4.2
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... (cached) awk
configure: Mill package version: 0.7-beta
configure: Mill ABI version: 4.2.0
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc -std=gnu99... /usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld
checking if the linker (/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm
checking the name lister (/usr/bin/nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-apple-darwin11.4.2 file names to x86_64-apple-darwin11.4.2 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin11.4.2 file names to toolchain format... func_convert_file_noop
checking for /usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm output from gcc -std=gnu99 object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for gcc -std=gnu99 option to produce PIC... -fno-common -DPIC
checking if gcc -std=gnu99 PIC flag -fno-common -DPIC works... yes
checking if gcc -std=gnu99 static flag -static works... no
checking if gcc -std=gnu99 supports -c -o file.o... yes
checking if gcc -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the gcc -std=gnu99 linker (/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin11.4.2 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for bash... /bin/bash
checking if dolt supports this host... yes, replacing libtool
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libmill.pc
config.status: executing depfiles commands
config.status: executing libtool commands
 ~/desktop/gramian/libmill/libmill-0.7-beta> make
  CC       libmill_la-chan.lo
  CC       libmill_la-cr.lo
  CC       libmill_la-debug.lo
  CC       libmill_la-list.lo
  CC       libmill_la-model.lo
  CC       libmill_la-poller.lo
  CC       libmill_la-slist.lo
  CC       libmill_la-stack.lo
  CC       libmill_la-tcp.lo
  CC       libmill_la-utils.lo
  CC       libmill_la-valbuf.lo
  CCLD     libmill.la
  CC       perf/go.o
  CCLD     perf/go
  CC       perf/ctxswitch.o
  CCLD     perf/ctxswitch
  CC       perf/chan.o
  CCLD     perf/chan
  CC       perf/chs.o
  CCLD     perf/chs
  CC       perf/chr.o
  CCLD     perf/chr
 ~/desktop/gramian/libmill/libmill-0.7-beta> make check
make  tests/example tests/go tests/cls tests/chan tests/choose tests/sleep tests/fdwait tests/tcp
  CC       tests/example.o
  CCLD     tests/example
  CC       tests/go.o
  CCLD     tests/go
  CC       tests/cls.o
  CCLD     tests/cls
  CC       tests/chan.o
  CCLD     tests/chan
  CC       tests/choose.o
tests/choose.c: In function ‘choosesender’:
tests/choose.c:55: error: ‘__COUNTER__’ undeclared (first use in this function)
tests/choose.c:55: error: (Each undeclared identifier is reported only once
tests/choose.c:55: error: for each function it appears in.)
tests/choose.c: In function ‘feeder2’:
tests/choose.c:71: error: ‘__COUNTER__’ undeclared (first use in this function)
tests/choose.c:72: error: redeclaration of ‘mill_clause__COUNTER__’ with no linkage
tests/choose.c:71: error: previous declaration of ‘mill_clause__COUNTER__’ was here
tests/choose.c:72: error: redefinition of ‘mill_val__COUNTER__’
tests/choose.c:71: error: previous definition of ‘mill_val__COUNTER__’ was here
tests/choose.c:72: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:71: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:72: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:71: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c: In function ‘main’:
tests/choose.c:98: error: ‘__COUNTER__’ undeclared (first use in this function)
tests/choose.c:108: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:108: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:118: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:118: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:127: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:127: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:137: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:137: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:139: error: redeclaration of ‘mill_clause__COUNTER__’ with no linkage
tests/choose.c:137: error: previous declaration of ‘mill_clause__COUNTER__’ was here
tests/choose.c:139: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:139: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:145: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:145: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:147: error: redeclaration of ‘mill_clause__COUNTER__’ with no linkage
tests/choose.c:145: error: previous declaration of ‘mill_clause__COUNTER__’ was here
tests/choose.c:147: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:147: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:164: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:164: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:167: error: redeclaration of ‘mill_clause__COUNTER__’ with no linkage
tests/choose.c:164: error: previous declaration of ‘mill_clause__COUNTER__’ was here
tests/choose.c:167: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:167: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:182: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:182: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:184: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:184: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:192: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:192: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:205: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:205: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:212: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:212: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:224: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:224: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:228: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:228: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:237: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:237: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:246: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:246: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:250: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:250: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:279: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:279: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:281: error: redeclaration of ‘mill_clause__COUNTER__’ with no linkage
tests/choose.c:279: error: previous declaration of ‘mill_clause__COUNTER__’ was here
tests/choose.c:281: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:281: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:293: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:293: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
tests/choose.c:302: error: duplicate label ‘mill_label__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_label__COUNTER__’ was here
tests/choose.c:302: error: duplicate label ‘mill_dummylabel__COUNTER__’
tests/choose.c:98: error: previous definition of ‘mill_dummylabel__COUNTER__’ was here
make[1]: *** [tests/choose.o] Error 1
make: *** [check-am] Error 2
 ~/desktop/gramian/libmill/libmill-0.7-beta> sudo make install
Password:
 ./install-sh -c -d '/usr/local/lib'
 ./doltlibtool   --mode=install /usr/bin/install -c   libmill.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libmill.lai /usr/local/lib/libmill.la
libtool: install: /usr/bin/install -c .libs/libmill.a /usr/local/lib/libmill.a
libtool: install: chmod 644 /usr/local/lib/libmill.a
libtool: install: ranlib /usr/local/lib/libmill.a
 ./install-sh -c -d '/usr/local/include'
 /usr/bin/install -c -m 644 libmill.h '/usr/local/include'
 ./install-sh -c -d '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 libmill.pc '/usr/local/lib/pkgconfig'
 ~/desktop/gramian/libmill/libmill-0.7-beta> gcc -rdynamic example.c -o example
i686-apple-darwin11-llvm-gcc-4.2: example.c: No such file or directory
i686-apple-darwin11-llvm-gcc-4.2: no input files
 ~/desktop/gramian/libmill/libmill-0.7-beta> cd tests
 ~/desktop/gramian/libmill/libmill-0.7-beta/tests> ls
chan		choose.c	cls.o		example.o	go.c		tcp.c
chan.c		cls		example		fdwait.c	go.o
chan.o		cls.c		example.c	go		sleep.c
 ~/desktop/gramian/libmill/libmill-0.7-beta/tests> gcc -rdynamic example.c -o example
Undefined symbols for architecture x86_64:
  "_mill_go_epilogue", referenced from:
      _main in cctEc6PB.o
  "_mill_go_prologue", referenced from:
      _main in cctEc6PB.o
  "_mill_msleep", referenced from:
      _worker in cctEc6PB.o
      _main in cctEc6PB.o
  "_mill_unoptimisable1", referenced from:
      _main in cctEc6PB.o
  "_mill_unoptimisable2", referenced from:
      _main in cctEc6PB.o
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
 ~/desktop/gramian/libmill/libmill-0.7-beta/tests> gcc -rdynamic example.c -o example -lmill
 ~/desktop/gramian/libmill/libmill-0.7-beta/tests>

**Comment by sustrik** [comment]
There's one patch in the current head that might help. Please, retry.

**Comment by sustrik** [comment]
No reply for 3 weeks. Closing the issue. Please, re-open in case of need.

**Comment by ihabbab** [comment]
Thanks Martin and sorry I got so busy with family things I had no time to check. Thank you for writing this great library. I do plan to use it soon.
