### ISSUE TITLE
Multi-core support?

### ISSUE THREAD

**Issue by JunfengJia** [sustrik/libmill#30]
Any though on this? most pc are multi-core now.

**Comment by sustrik** [comment]
Run mulitple processes.

**Comment by jhawk28** [comment]
This means that libmill coroutines are in the spirit of Lua, not Go.

**Comment by sustrik** [comment]
Possibly, but the syntax is stolen from Go.

**Comment by sustrik** [comment]
Not clear what can be done here. Closing the issue until there are more down-to-earth proposals.
