### ISSUE TITLE
avoid assert from assert.h

### ISSUE THREAD

**Issue by nickdesaulniers** [sustrik/libmill#34]
we should also take a look at the use of assert throughout the code base, since configuring with `cmake -DCMAKE_BUILD_TYPE=Release ..` for optimized builds will use the `-NDEBUG` flag which will remove the expressions within assert statements entirely. That, or possibly force cmake to not build with that flag for the tests at least.

The problem with assert from assert.h is that they're meant to be removed with `-NDEBUG`.  It would be preferable to have an assert macro that either checked the return code or didn't based on symbol definition at compile time, not whether to execute code and test or not at all.

**Comment by sustrik** [comment]
Asserts should not be optional. The minimal overhead they impose is worth of having an implementation that fails early rather than exhibit undefined behaviour.

**Comment by nickdesaulniers** [comment]
> The minimal overhead they impose is worth of having an implementation that fails early rather than exhibit undefined behaviour.

I agree.  My point is that if someone makes an optimized build with cmake, they'll get removed.  Therefor, we should write our own assert function that doesn't get removed when `NDEBUG` is defined.

**Comment by sustrik** [comment]
Hm, isn't there a way to instruct CMake not to define NDEBUG? Or would that switch the optimisation off? /me is not familiar with CMake.

**Comment by sustrik** [comment]
http://stackoverflow.com/questions/22140520/how-to-enable-assert-in-cmake-release-mode

**Comment by sustrik** [comment]
Anyway, if you decide there's no easy way to trick CMake to retain asserts, implementing our own is easy.

**Comment by nickdesaulniers** [comment]
we could recommend that people looking to build with cmake use:
`cmake -DCMAKE_C_FLAGS='-O3' ..` to add the optimization flag without defining `-NDEBUG`.

**Comment by sustrik** [comment]
That's ugly. If there's no way to do it transparently for the user, let's go for custom asserts.

**Comment by nickdesaulniers** [comment]
can we reopen this issue to track the work?

**Comment by reqshark** [comment]
@nickdesaulniers can we use cmake 2.7 instead of cmake 3?  If so, I'll update our travis config to test the cmake build too. Travis uses 2.7, see: https://github.com/travis-ci/travis-ci/issues/2030

**Comment by nickdesaulniers** [comment]
@reqshark more than likely

**Comment by sustrik** [comment]
Fixed. mill_assert() is used instead of assert().
