### ISSUE TITLE
Need partial read/write support

### ISSUE THREAD

**Issue by tirips** [sustrik/libmill#48]
tcpsend() and tcprecv()

**Comment by sustrik** [comment]
What's partial read/write?

**Comment by tirips** [comment]
tcprecv(s, buf, len, -1) returns immediately when any data is received without waiting for all len bytes

**Comment by sustrik** [comment]
Just use a deadline. That does exactly what you want.

**Comment by tirips** [comment]
I want it to keep waiting until some data is read.

**Comment by sustrik** [comment]
tcprecv(s, buf, 1, -1)

**Comment by tirips** [comment]
Clever trick. It would be better that there is a more intuitive and convenient interface.

**Comment by sustrik** [comment]
I actually prefer the solution above because it makes user articulate what they want clearly. How many bytes to unconditionally wait for, deadline for those, deadline for any additional bytes etc.

**Comment by tirips** [comment]
Maybe I'm used to the behavior of posix and go. Thanks for your approach.
