### ISSUE TITLE
tests/tcp hangs on FreeBSD

### ISSUE THREAD

**Issue by ebfe** [sustrik/libmill#50]
tests/tcp hangs forever in poll() on FreeBSD.

truss output:

    ...
    socket(PF_INET,SOCK_STREAM,0)                    = 3 (0x3)
    fcntl(3,F_GETFL,)                                = 2 (0x2)
    fcntl(3,F_SETFL,O_NONBLOCK|0x2)                  = 0 (0x0)
    setsockopt(0x3,0xffff,0x4,0x7fffffffe78c,0x4,0xfffffff4) = 0 (0x0)
    setsockopt(0x3,0xffff,0x800,0x7fffffffe78c,0x4,0xfffffff4) = 0 (0x0)
    bind(3,{ AF_INET 0.0.0.0:5555 },16)              = 0 (0x0)
    listen(0x3,0xa,0x10,0x7fffffffe78c,0x4,0xfffffff4) = 0 (0x0)
    sigprocmask(SIG_BLOCK,0x0,0x0)                   = 0 (0x0)
    socket(PF_INET,SOCK_STREAM,0)                    = 4 (0x4)
    fcntl(4,F_GETFL,)                                = 2 (0x2)
    fcntl(4,F_SETFL,O_NONBLOCK|0x2)                  = 0 (0x0)
    setsockopt(0x4,0xffff,0x4,0x801857c7c,0x4,0x800fd5e80) = 0 (0x0)
    setsockopt(0x4,0xffff,0x800,0x801857c7c,0x4,0x800fd5e80) = 0 (0x0)
    connect(4,{ AF_INET 255.127.0.0:5555 },16)       ERR#36 'Operation now in progress'
    sigprocmask(SIG_BLOCK,0x0,0x0)                   = 0 (0x0)
    sigprocmask(SIG_SETMASK,0x0,0x0)                 = 0 (0x0)
    accept(3,0x0,0x0)                                ERR#35 'Resource temporarily unavailable'
    sigprocmask(SIG_BLOCK,0x0,0x0)                   = 0 (0x0)
    poll({4/POLLOUT 3/POLLIN},2,-1)                  ERR#4 'Interrupted system call'

The following patch makes the test pass:

```diff
diff --git a/tests/tcp.c b/tests/tcp.c
index d30d75c..6f75d36 100644
--- a/tests/tcp.c
+++ b/tests/tcp.c
@@ -28,6 +28,7 @@
 #include "../libmill.h"
 
 void client(int port) {
+    msleep(now()+100);
     tcpsock cs = tcpconnect("127.0.0.1", port, -1);
     assert(cs);
 
```

I guess these connect/accept should be synchronized in some way.

**Comment by sustrik** [comment]
Look at this: `connect(4,{ AF_INET 255.127.0.0:5555 },16)`

**Comment by sustrik** [comment]
And it doesn't happen with debug build :|

**Comment by ebfe** [comment]
with the msleep() call this turns into `connect(4,{ AF_INET 0.0.0.0:5555 },16)` which doesn't look correct either.

**Comment by sustrik** [comment]
I even see ` 116.237.68.40:5555` here.

**Comment by sustrik** [comment]
Ok, the problem is that inet_pton creates in_addr, while the program assume it's sockaddr_in. I will fix this shortly.

**Comment by sustrik** [comment]
Fixed. Please, re-check and close the issue if it works for you.

**Comment by ebfe** [comment]
`connect(4,{ AF_INET 127.0.0.1:5555 },16)`
Works. Thanks.
