### ISSUE TITLE
channel value destructor

### ISSUE THREAD

**Issue by jkarneges** [sustrik/libmill#53]
I'd like to be able to pass a complex object via pointer across a channel and have it be freed after it is no longer needed (e.g. after it is read, or if the channel is closed before it is read). I think all that's needed to solve this is for the app to be able to pass a destructor function when sending a value, which libmill can call when it is done with the value.

**Comment by sustrik** [comment]
Just read all the values from the channel before closing it. That way you can deallocate each one as needed.

**Comment by jkarneges** [comment]
Ah yes that seems reasonable, thanks.
