### ISSUE TITLE
Unix sockets

### ISSUE THREAD

**Issue by ebfe** [sustrik/libmill#58]
Is there any interest in supporting unix sockets?

**Comment by sustrik** [comment]
It would be nice IMO, but it's not on my roadmap in the near future.

**Comment by ebfe** [comment]
I gave it a quick first shot: https://github.com/ebfe/libmill/commit/207f6019e23b46ebb5a9576be0e89eb6cdef4814

It's mostly `cp tcp.c unix.c` s/tcp/unix/g. Most of the send/recv code could be unified with something like  socksend(int fd, struct sock_buffer, ...) or similar.

**Comment by sustrik** [comment]
Looks good. Would you like to make a pull request?
