### ISSUE TITLE
How to resume a coroutine from application code?

### ISSUE THREAD

**Issue by raksoras** [sustrik/libmill#79]
Sorry this is more like a question than a bug report but I couldn't find any example of how to do this. I believe calls like tcprecv(), tcpflush() and fdwait() internally yield coroutine when they are about to block and resume it when the socket is ready (using epoll etc.?). But if I explicitly call yield() from my coroutine how can my application code resume that specific coroutine later? Is there anything like a coroutine handle returned by go() call that can be stored and used later to resume the coroutine?

**Comment by sustrik** [comment]
It's done on a round-robin basis. Imagine all the coroutines that can be possibly resumed being arranged in a circle. When one of them yields, next one is resumed.

**Comment by raksoras** [comment]
Thanks for the quick reply.

So when the coroutine calls yield() it is still runnable on next round-robin dispatch? I was wondering if I wanted to use something like libuv library along with libmill -to use async File IO provided by libuv, for example - how would I use it. My design was to call libuv's async file IO operation from libmill coroutine and then yield immediately from my coroutine after somehow marking that coroutine as NON_RUNNABLE or BLOCKED. Then when the libuv calls a callback for file IO completion later, I'd resume the yielded coroutine explicitly from my code. I have used this approach with Lua coroutines by storing Lua coroutine's handle in libuv's async IO request object so that I can resume it form the libuv completion callback. For this approach to work however, application code needs A) an access to libmill coroutine handle/ID of some sort and B)ability to suspend/resume certain specific coroutine by that handle outside libmill's builtin coroutine scheduler. Having these two capabilities would make it possible to integrate libmill with other event IO libraries. I believe libmill must be doing something similar internally in calls like tcpreceive(), fdwait() etc. to avoid having coroutine resumed when the IO call is still blocked?

Is this likely to be supported at all or this is contra-indicated with libmill design philosophy?

**Comment by sustrik** [comment]
Just create a channel, call chr() on it, the coroutine will block. Once you want to unblock it, send a message to the channel.

**Comment by raksoras** [comment]
Ah, that would work. Thanks! Please feel free to close this issue.

One last question, are libmill coroutines are stackful? Can I block by calling chr() or yield from a function call nested arbitrary levels deep or only from the function call that is on the top of the stack?

**Comment by sustrik** [comment]
You can yield from any function. Each coroutine has its own stack.

**Comment by raksoras** [comment]
Thanks!
