### ISSUE TITLE
Missing anl library

### ISSUE THREAD

**Issue by sustrik** [sustrik/libmill#89]
When trying to compile a test by hand:

    sustrik@sustrik-glaptop:~/libmill/tests$ gcc -o tcp tcp.c -lmill
    //usr/local/lib/libmill.a(libmill_la-ip.o): In function `ipremote':
    /home/sustrik/libmill/ip.c:262: undefined reference to `getaddrinfo_a'
    /home/sustrik/libmill/ip.c:273: undefined reference to `gai_cancel'
    /home/sustrik/libmill/ip.c:278: undefined reference to `gai_error'

Why isn't anl library dragged in automatically? (adding -lanl helps)

**Comment by nirs** [comment]
Because these symbols come from a shared library?

**Comment by sustrik** [comment]
Uh. I've configured with --disable-shared and then forgot about that. That's why. I'm closing the ticket.
