### ISSUE TITLE
cmake build broken

### ISSUE THREAD

**Issue by ebfe** [sustrik/libmill#94]
...
    [ 91%] Linking C executable tests/tcp
    libmill.a(ip.c.o): In function `ipremote':
    ip.c:(.text+0xc3f): undefined reference to `getaddrinfo_a'
    ip.c:(.text+0xd0b): undefined reference to `gai_cancel'
    ip.c:(.text+0xd88): undefined reference to `gai_error'
    collect2: error: ld returned 1 exit status
    CMakeFiles/test_tcp.dir/build.make:95: recipe for target 'tests/tcp' failed
    make[2]: *** [tests/tcp] Error 1
    CMakeFiles/Makefile2:696: recipe for target 'CMakeFiles/test_tcp.dir/all' failed
    make[1]: *** [CMakeFiles/test_tcp.dir/all] Error 2
    Makefile:94: recipe for target 'all' failed
    make: *** [all] Error 2

I guess `-lanl` is missing from the linker flags. Not sure where/how to add it.

**Comment by sustrik** [comment]
I am out of town for a week. I'll give it a look afterwards. Patches welcome in the meantime, of course.

**Comment by reqshark** [comment]
@ebfe and @sustrik, after #102 and #103 I believe this issue is resolved

**Comment by ebfe** [comment]
I don't think this is resolved. It just broken in a different way. Stack guards and DNS are always disabled. The cmake build makes no effort to detect mprotect/posix_memalign/... so it always builds without stack guard or dns even on Linux.

**Comment by procedural** [comment]
@ebfe did you changed original CMakeLists.txt file? Could you share it so I could test it?

**Comment by ebfe** [comment]
I didn't change anything in the CMakeLists. The above build error disappeared because due to changes in how libmill is configured. It now requires HAVE_LIBANL, HAVE_MPROTECT, HAVE_POSIX_MEMALIGN defines to enable dns and the stack guard. Since the cmake based build doesn't do any checks/define any of these stack-guard and dns is always disabled.

**Comment by procedural** [comment]
> It now requires HAVE_LIBANL, HAVE_MPROTECT, HAVE_POSIX_MEMALIGN defines to enable dns and the stack guard.

Ah, yes, if I define those I can reproduce the errors you get.

**Comment by sustrik** [comment]
Yes. CMake should check for presence of getaddrinfo_a and add anl to the list of linked libraries, if present.
