### ISSUE TITLE
time based tests are flaky

### ISSUE THREAD

**Issue by ebfe** [sustrik/libmill#96]
On a small arm system, most of the time based tests randomly fail

```
FAIL: tests/fdwait
==================

fdwait: tests/fdwait.c:87: main: Assertion `diff > 40 && diff < 60' failed.
FAIL tests/fdwait (exit status: 134)

FAIL: tests/tcp
===============

tcp: tests/tcp.c:77: main: Assertion `diff > -10 && diff < 10' failed.
FAIL tests/tcp (exit status: 134)
```

Not sure if the problem is the slow cpu or the low resolution of CLOCK_MONOTONIC (clock_getres reports 10ms). Switching to gettimeofday based now() does not help.

**Comment by sustrik** [comment]
Likely the combination of both. What kind of differences are you seeing?

**Comment by ebfe** [comment]
The `-10 < diff < 10` asserts mostly fail with diff ~17.  tests/fdwait mostly fails with diff == 60 (checked for < 60).

**Comment by sustrik** [comment]
I've increased the tolerances to 20ms. Please, re-check and close the issue if appropriate.

**Comment by ebfe** [comment]
Survived 100 runs without failure.
